version: '3.3'
services:

 postgres:
   image: postgres:latest
   environment:
     - POSTGRES_DB=django
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=django

 django:
   image: ulyana2211/django:latest
   ports:
     - "8000:8000"
   volumes:
     - ./:/app/
   depends_on:
     - postgres
   environment:
     - DATABASE_HOST=postgres
   command: |
     python manage.py runserver 0.0.0.0:8000