version: '3.3'
services:

 postgres:
   image: postgres:latest
   environment:
     - POSTGRES_DB=django
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=django

 redis:
   image: redis:latest

 django:
   image: ulyana2211/django:latest
   ports:
     - "8000:8000"
   volumes:
     - ./shop/:/app/
   depends_on:
     - postgres
     - redis
   environment:
     - POSTGRES_NAME=django
     - POSTGRES_USER=django
     - POSTGRES_PASS=django
     - POSTGRES_HOST=postgres
     - REDIS_HOST=redis
   command: |
     python manage.py runserver 0.0.0.0:8000

 worker:
   image: ulyana2211/django:latest

   volumes:
     - ./shop/:/app/
   depends_on:
     - postgres
     - redis
   environment:
     - POSTGRES_NAME=django
     - POSTGRES_USER=django
     - POSTGRES_PASS=django
     - POSTGRES_HOST=postgres
     - REDIS_HOST=redis
   command: |
     python manage.py runserver rqworker